= Quickstart
Malcolm Rozé <malcolm@sansenshimizu.com>
:description: Sakura Boot — mapper module — quickstart page documentation

The quickstart documentation will demonstrate how to install and use Sakura Boot with the mapper module to create a simple API application with mapper and DTO.

== Prerequisites

See xref:sakura-boot::requirements.adoc[] for prerequisites.

== Base application

If a base application is needed before this quickstart, see the xref:sakura-boot-basic::quickstart.adoc[basic quickstart] section.

== Project structure

Multiple structures are possible when working with Sakura Boot. +
For this quickstart rest API project, the structure is as follows:

[listing]
----
📂 project <.>
  📂 src <.>
    📂 main
        📂 java <.>
            📂 com.example.demo <.>
                📂 business <.>
                    📄 SimpleDto.java
                    📄 SimpleMapper.java
                    📄 SimpleService.java
                📂 persistence <.>
                    📄 SimpleEntity.java
                    📄 SimpleRepository.java
                📂 presentation <.>
                    📄 SimpleController.java
                📄 DemoApplication.java <.>
        📂 resources <.>
            📄 application.properties
            📄 application.yml
  📄 build.gradle.kts <.>
  📄 settings.gradle.kts <.>
  📄 pom.xml <.>
  📄 docker-compose.yml <.>
----

<.> The root directory of the project.
<.> Contains the source code of the project.
<.> Contains the java code.
<.> The java code must be in the package com.example.demo (replace to the actual package name).
<.> The business layer of the application (here the services, mappers, and DTOs).
<.> The persistence layer of the application (here the entities and repositories).
<.> The presentation layer of the application (here the controllers).
<.> The application entry point.
<.> Contains the resources configuration files.
<.> The build file (for Gradle).
<.> The settings file (for Gradle).
<.> The pom file (for Maven).
<.> The docker compose file (optional).

IMPORTANT: To initialize a Spring Boot application, go to https://start.spring.io/[window=_blank].
From there, it will be easier to create a new project.

== Installation

To install with predefined dependencies for a production-ready application, add one starter to the project dependencies:

* With Maven:

This includes the basic functionalities of sakura boot, the necessary spring boot starter, and a runtime postgresql.
And the mapper module for the second dependency.

[,xml,subs=+attributes]
----
<dependency>
    <groupId>org.sansenshimizu.sakuraboot</groupId>
    <artifactId>sakura-boot-starter-predefined-basic</artifactId>
    <version>{release-version}</version>
</dependency>
<dependency>
    <groupId>org.sansenshimizu.sakuraboot</groupId>
    <artifactId>sakura-boot-mapper</artifactId>
    <version>{release-version}</version>
</dependency>
----

This includes all the modules of sakura boot, the necessary spring boot starter, mapstruct, ehcache3 as cache provider, and a runtime postgresql.

[,xml,subs=+attributes]
----
<dependency>
    <groupId>org.sansenshimizu.sakuraboot</groupId>
    <artifactId>sakura-boot-starter-predefined-all-module</artifactId>
    <version>{release-version}</version>
</dependency>
----

* With Gradle:

This includes the basic functionalities of sakura boot, the necessary spring boot starter, and a runtime postgresql.
And the mapper module for the second dependency.

[,kotlin,subs=+attributes]
----
implementation("org.sansenshimizu.sakuraboot:sakura-boot-starter-predefined-basic:{release-version}")
implementation("org.sansenshimizu.sakuraboot:sakura-boot-mapper:{release-version}")
----

This includes all the modules of sakura boot, the necessary spring boot starter, mapstruct, ehcache3 as cache provider, and a runtime postgresql.

[,kotlin,subs=+attributes]
----
implementation("org.sansenshimizu.sakuraboot:sakura-boot-starter-predefined-all-module:{release-version}")
----

TIP: Maven is recommended for developers who never use both Maven and Gradle.

Here is a simple pom.xml file that includes the predefined basic module starter and the mapper module with lombok, spring boot devtools, and spring boot docker compose:

[,xml,subs=+attributes]
.pom.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>{spring-version}</version>
    <relativePath/>
  </parent>
  <groupId>com.example</groupId>
  <artifactId>demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>demo</name>
  <description>Demo project for Sakura Boot</description>
  <properties>
    <java.version>{java-version}</java.version>
  </properties>
  <dependencies>
    <dependency>
        <groupId>org.sansenshimizu.sakuraboot</groupId>
        <artifactId>sakura-boot-starter-predefined-basic</artifactId>
        <version>{release-version}</version>
    </dependency>
    <dependency>
        <groupId>org.sansenshimizu.sakuraboot</groupId>
        <artifactId>sakura-boot-mapper</artifactId>
        <version>{release-version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-docker-compose</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct-processor</artifactId>
        <version>{mapstruct-version}</version>
        <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
            </exclude>
          </excludes>
        </configuration>
      </plugin>
      <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.10.0</version>
            <configuration>
                <source>{java-version}</source>
                <target>{java-version}</target>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.mapstruct</groupId>
                        <artifactId>mapstruct-processor</artifactId>
                        <version>{mapstruct-version}</version>
                    </path>
                    <path>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                    </path>
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
  </build>
</project>
----

Here is an equivalent simple build.gradle.kts.

[,kotlin,subs=+attributes]
.build.gradle.kts
----
plugins {
  java
  id("org.springframework.boot") version "{spring-version}"
  id("io.spring.dependency-management") version "1.1.6"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of({java-version})
  }
}

configurations {
  compileOnly {
    extendsFrom(configurations.annotationProcessor.get())
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation("org.sansenshimizu.sakuraboot:sakura-boot-starter-predefined-basic:{release-version}")
  implementation("org.sansenshimizu.sakuraboot:sakura-boot-mapper:{release-version}")
  compileOnly("org.projectlombok:lombok")
  developmentOnly("org.springframework.boot:spring-boot-devtools")
  developmentOnly("org.springframework.boot:spring-boot-docker-compose")
  annotationProcessor("org.projectlombok:lombok")
  annotationProcessor("org.mapstruct:mapstruct-processor:{mapstruct-version}")
}
----

== Configuration

The configuration of the project is the same as the xref:sakura-boot-basic::quickstart.adoc#_configuration[basic
quickstart] section.

CAUTION: For a production-ready application, remove the spring.jpa.hibernate.ddl-auto property.

== Create the application

The next part is to write the application code. +
The application will use UUID as the primary key of the entity.
It is possible to use any other primary key (e.g., Long, String, etc).

Again, if a base application is needed before this quickstart, see the xref:sakura-boot-basic::quickstart.adoc[basic
quickstart] section.

=== Service

The service in SimpleService.java can change based on the modules that are used.

Here is an example of the service that uses the mapper module.

[,java]
.SimpleService.java
----
package com.example.demo.business;

import java.util.UUID;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;

import org.sansenshimizu.sakuraboot.basic.api.business.BasicService;
import org.sansenshimizu.sakuraboot.mapper.api.Mappable;

import com.example.demo.persistence.SimpleEntity;
import com.example.demo.persistence.SimpleRepository;

@Service
public class SimpleService
    implements BasicService<SimpleEntity, UUID>, Mappable<SimpleEntity, SimpleDto> {

    private final SimpleRepository repository;

    private final ObjectMapper objectMapper;

    private final SimpleMapper mapper;

    @Override
    public Class<Simple> getEntityClass() {

        return Simple.class;
    }

    @Override
    public Class<SimpleDto> getDtoClass() {

        return SimpleDto.class;
    }

    // Required arg constructor, getters, etc. if lombok is not used.
}
----

For lombok users, add the annotation on top of the class:

[,java]
----
@Getter
@RequiredArgsConstructor
@Service
----

The simple application with the mapper module is now ready to be used.

==== Mapping

An application with mapping needs a DTO and a mapper file, it will be the SimpleDto.java and SimpleMapper.java.

Here is an example of the DTO file.

[,java]
.SimpleDto.java
----
package com.example.demo.business;

import java.io.Serial;
import java.util.List;
import java.util.UUID;

import org.apache.commons.lang3.tuple.Pair;

import org.sansenshimizu.sakuraboot.mapper.dto.AbstractBasicDto;

public class SimpleDto extends AbstractBasicDto<UUID> {

    @Serial
    private static final long serialVersionUID = 2152253389776242470L;

    private final Long id;

    private final String name;

    // Required arg constructor, getters, etc. if lombok is not used.
}
----

For lombok users, add the annotation on top of the class:

[,java]
----
@Builder(toBuilder = true)
@Jacksonized
@Getter
----

Here is an example of the mapper file.

[,java]
.SimpleMapper.java
----
package com.example.demo.business;

import org.mapstruct.Mapper;

import org.sansenshimizu.sakuraboot.mapper.api.BasicMapper;

import com.example.demo.persistence.SimpleEntity;

@Mapper(config = BasicMapper.class)
public interface SimpleMapper extends BasicMapper<SimpleEntity, SimpleDto> {}
----

== Usage

The usage is the same as the xref:sakura-boot-basic::quickstart.adoc#_usage[basic quickstart] section.

== Next steps

For more information on how to build and run a Spring Boot application, see https://spring.io/guides/gs/spring-boot[here,window=_blank].

For more information about the spring-boot-docker-compose for local development with docker support, see https://docs.spring.io/spring-boot/reference/features/dev-services.html#features.dev-services.docker-compose[here,window=_blank].

The quickstart application creates only one entity.
The next step could be to add more entities with the necessary fields.
For each new entity follow the same steps.

When building an application with different entities, it is possible to create relations between them. +
For more information, see the xref:sakura-boot::relationship.adoc[] section.

When building an application, it is important to also create tests. +
Sakura Boot provides a test framework that can be used to test the application.
It supports unit tests, integration tests, and functional tests. +
For more information, see the xref:testing.adoc[] section.

To customize the configuration for the application requirements, see the xref:configuration.adoc[] section.

If the quickstart section is not sufficient, other examples are available at the xref:sakura-boot::examples.adoc[] section.
