site:
  title: Sakura Boot
  start_page: sakura-boot::index.adoc
content:
  sources:
    - url: https://github.com/Sansen-Shimizu/sakura-boot.git
      branches: HEAD
      start_path: docs
runtime:
  fetch: true
ui:
  bundle:
    url: ./antora-ui-sakura-boot/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
