site:
  url: https://sakuraboot.sansenshimizu.org/
  title: Sakura Boot
  start_page: sakura-boot::index.adoc
  robots: allow
content:
  sources:
    - url: https://github.com/Sansen-Shimizu/sakura-boot.git
      branches: [ HEAD, '0.*', '!0.1.x' ]
      start_path: docs
runtime:
  fetch: true
ui:
  bundle:
    url: ./antora-ui-sakura-boot/build/ui-bundle.zip
    snapshot: true
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true

