site:
  title: Sakura Boot
  start_page: sakura-boot::index.adoc
content:
  sources:
    - url: ./.. #https://github.com/Sansen-Shimizu/sakura-boot.git
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: ./antora-ui-sakura-boot/build/ui-bundle.zip
    snapshot: true
