site:
  url: https://sakuraboot.sansenshimizu.org/
  title: Sakura Boot
  start_page: sakura-boot::index.adoc
  robots: allow
content:
  sources:
    - url: ./.. #https://github.com/Sansen-Shimizu/sakura-boot.git
      branches: [ HEAD, '0.*', '!0.1.x' ]
      start_paths:
        - docs
        - sakura-boot-project/*/docs
        - sakura-boot-project/sakura-boot-test/*/docs
runtime:
  fetch: true
ui:
  bundle:
    url: ./antora-ui-sakura-boot/build/ui-bundle.zip
    snapshot: true
output:
  dir: ./build/documentation
  destinations:
    - provider: archive
      path: ./build/documentation/documentation.zip
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true

